### ISSUE TITLE
transferring to self causes loss of server coin.

### ISSUE THREAD

**Issue by Wingysam** [Bibliofile/Blockheads-MessageBot#16]
Wingysam: /check
SERVER: Wingysam currently has 60 sky bucks.
Wingysam: /transfer 5 Wingysam
SERVER: Transferred 5 sky bucks from Wingysam to Wingysam.
Wingysam: /check
SERVER: Wingysam currently has 55 sky bucks.

**Comment by Bibliofile** [comment]
Closing here, transferred to the correct Repo.
