### ISSUE TITLE
I.E. can't load bot

### ISSUE THREAD

**Issue by dapersonmgn** [Bibliofile/Blockheads-MessageBot#17]
Skeeve seems to be unable to load the bot, It tells him he needs to update the bot. Maybe the issue is with this?
https://github.com/Bibliofile/Blockheads-MessageBot/blob/master/dev/header.js#L5L8
Why would the MessageBot version be invalid if crossorigin does not exist?

**Comment by Bibliofile** [comment]
Resolved -- rather bad practice on my part editing just the distribution file, but it should work now for everyone... It was a caching issue.
