### ISSUE TITLE
PvP messages death not working.

### ISSUE THREAD

**Issue by Wingysam** [Bibliofile/Blockheads-MessageBot#20]
I noticed that the death trigger does not work. I do not think there is a log entry when a player dies.

**Comment by dapersonmgn** [comment]
Is the world a 1 hit death world? Deaths don't log in those worlds.

**Comment by Bibliofile** [comment]
I believe they don't log in custom worlds at all - I tried killing myself in a custom world with normal health / death settings and nothing...

**Comment by dapersonmgn** [comment]
Dang it! I'll add a warning to the extension about that.

**Comment by Bibliofile** [comment]
Marking this as resolved as the problem isn't with the bot itself, and it seems it has been "fixed".
