### ISSUE TITLE
Chat screen automatically shifts to bottom when new messages arrive

### ISSUE THREAD

**Issue by jemnidad** [Bibliofile/Blockheads-MessageBot#21]
I find this annoying, when I'm trying to scroll up and read some history in the chat window. Then a message arrives and pops the window focus back to the new message, so I have to find my place all over again. Could this autofocus be disabled?

**Comment by Bibliofile** [comment]
The bot will now detect if you have scrolled up, and shouldn't scroll you down unless you are already scrolled all the way down, what do you think of this? Is a separate setting still important?

**Comment by jemnidad** [comment]
Nope, that's perfect.  I noticed it working today.  Thank you so much.
