### ISSUE TITLE
The limit on triggers is not working

### ISSUE THREAD

**Issue by jemnidad** [Bibliofile/Blockheads-MessageBot#23]
Players are still allowed to use triggers for commands way past the limit I have set.

**Comment by Gerrit0** [comment]
As discussed a while back on Skylands, this happens because only user triggers are checked, those defined by extensions are not checked.

**Comment by jemnidad** [comment]
But I see it for user triggers.  I've got one that triggers on "gtg" for
example and it keeps on firing way after the limit of 3.

**Comment by Bibliofile** [comment]
I tried reproducing this on Arena yesterday and was unable to get more than 3 responses from the bot for a single message. 

Is this what your limit is set to? If so, I believe this is fixed.

**Comment by Bibliofile** [comment]
This is resolved in 6.0.
