### ISSUE TITLE
Occasionally see messages triggered for the wrong login count

### ISSUE THREAD

**Issue by jemnidad** [Bibliofile/Blockheads-MessageBot#24]
So, I have a message that is meant to be triggered by new players who have never joined before. The join trigger fires if the player has joined between 0 and 1 times.  However, I see it fire for players who have been on way more than that.  Even players who were just on a few minutes ago.  

I know I've seen it occur after restarting the bot, but I've also seen it fire incorrectly with the bot running already.

**Comment by Bibliofile** [comment]
Looking into this now. :)

**Comment by Bibliofile** [comment]
The bot now saves log info between launches, which has fixed this issue :)
