### ISSUE TITLE
Disconnection messages when banned

### ISSUE THREAD

**Issue by dapersonmgn** [Bibliofile/Blockheads-MessageBot#32]
http://forums.theblockheads.net/t/when-a-player-is-banned-they-cant-see-the-world/49241?u=billk123
Following Ronnie's idea.
The MessageBot should not send any leave messages if the user is banned.

Solution Idea: Track players online. If the player leaving was in the array or obj or whatever that contains online players. Then send the leave message.

**Comment by Bibliofile** [comment]
This is a good idea, will implement.

**Comment by Bibliofile** [comment]
Fixed as of e82187e66bb825d19223cc74f3b912bb1d05b924 - will close when merged.

**Comment by Bibliofile** [comment]
This is now a thing :)
