### ISSUE TITLE
Loading the same extension multiple times

### ISSUE THREAD

**Issue by dapersonmgn** [Bibliofile/Blockheads-MessageBot#35]
On iOS if you manage to click the install button fast enough for an extension, you can install it multiple times.

**Comment by Bibliofile** [comment]
Caused by efd7a665e3c77338497bbf6a9e13e00a197073d7 - the `is-loading` class only works on buttons. Will fix.

**Comment by dapersonmgn** [comment]
Seems fixed. :D

**Comment by Bibliofile** [comment]
Yep, this is fixed in the latest version :) Extensions could potentially be loaded multiple times, but only the first time will the code be executed.
