### ISSUE TITLE
When a player joins no message appears in the console

### ISSUE THREAD

**Issue by dapersonmgn** [Bibliofile/Blockheads-MessageBot#36]
I'm entirely sure if this is a bug, but when a player joins the server it no longer displays the 
DAPERSON - IP - DEVICE_ID
or something like that anymore. It doesn't say the player joined the world at all.

**Comment by Bibliofile** [comment]
When a player joins, it should display using a slightly different format: 

https://github.com/Bibliofile/Blockheads-MessageBot/blob/master/dev/console/index.js#L43-L49

This is a result of the poll [here](http://forums.theblockheads.net/t/the-message-bot/18040/441?u=bibliophile)

**Comment by dapersonmgn** [comment]
I'm not getting any of those messages.

**Comment by Bibliofile** [comment]
Are they showing up for you again?

**Comment by dapersonmgn** [comment]
Yeah. :D
