### ISSUE TITLE
No "start" script

### ISSUE THREAD

**Issue by Wingysam** [Bibliofile/Blockheads-MessageBot#39]
I'm running Node v6.10.0
I just cloned.
I'm using macOS 10.12.3 (Sierra)
To reproduce, Go to ~/Blockheads-MessageBot, `$ npm start:mac`

Building it failed.
Note, I didn't have Gulp, I installed it with `$ npm install gulp`. `npm run build` causes Gulp to exit with code 1.

**Comment by Bibliofile** [comment]
Has this been resolved per our discussion in discord?

**Comment by Wingysam** [comment]
Yes, I forgot `run`.
