### ISSUE TITLE
The /transfer command clears accounts

### ISSUE THREAD

**Issue by jemnidad** [Bibliofile/Blockheads-MessageBot#8]
If a player uses /transfer, it clears their account.  

I had a player with 30 Sky bucks transfer 2 of them to another player.  Next he checked and his account had a balance of 0.

In addition, an admin even with a balance of 0 can transfer any amount of currency to another player.

**Comment by Bibliofile** [comment]
I've released a fix for this in the Blockheads-Server-Currency repository :) Closing here as it is isn't a part of the MessageBot itself.
